y7_look = {...
    'MAT','MAT';...
    '/1' ,'OP1';...
    '/2' ,'OP2';...
    '/3' ,'OP3';...
    '/4' ,'OP4';...
    '/4' ,'OP4';...
    '/5' ,'OP5';...
    '/6' ,'OP6';...
    'ACT','ACT';...
    'ELG','ELG';...
    'SCIp','PHY';...
    'SCIc','CHE';...
    'SCIb','BIO';...
    'HPQ','HPQ';...
    'GAM','GAM'};
