y7_look = {...
    'ELG','ELG';...
    'SCI','SCI';...
    'MAT','MAT';...
    'FNU','TEC';...
    'DT','TEC';...
    'GerSpa','ML0';...
    ' a','ML1';...
    '/1 ','ML1';...
    'FreGer','ML0';...
    '/2 ','ML2';...
    ' b','ML2';...
    'MUS','MUS';...
    'HIS','HIS';...
    'GEO','GEO';...
    'LAT','LAT';...
    'REL','REL';...
    'ICT','ICT';...
    'PED','PED';...
    'PSE','PSE';...
    'ACT','ACT';...
    'ART','ART';...
    'GAM','GAM'};
