y7_look = {...
    'MAT','MAT';...
    'GEO','GEO';...
    'REL','REL';...
    'PHY','PHY';...
    'CHE','CHE';...
    'BIO','BIO';...
    '/1' ,'OP1';...
    '/2' ,'OP2';...
    '/3' ,'OP3';...
    '/4' ,'OP4';...
    'PED','PED';...
    'PSE','PSE';...
    'ACT','ACT';...
    'ELT','ELG';...
    'HIS','HIS';...
    'GAM','GAM'};
